version: '3'
services:
  website:
    user: "www-data"
    build:
      dockerfile: Dockerfile
    container_name: converthub-website
    ports:
      - "8002:80"
      - "8443:443"
    restart: always