version: '3'
services:
  website:
    build:
      dockerfile: Dockerfile
    container_name: converthub-website
    ports:
      - "8002:80"
      - "8443:443"
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
